server:
  port: 8080
  tomcat:
    connection-timeout: 120000  # 120秒连接超时
    max-http-form-post-size: 5000MB  # 与multipart配置保持一致

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/kk3k3_fun?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 200309
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # Redis配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 10000
      # 如果需要密码，取消注释下一行
      # password: 
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB
      # 启用解析失败时的容错处理
      resolve-lazily: true
      # 设置临时存储目录
      location: /tmp
  mvc:
    servlet:
      load-on-startup: 1  # 确保Servlet立即初始化

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.ligg.entity
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT配置
jwt:
  # token有效期（单位：秒）
  expiration: 86400  # 24小时
  # token头部
  header: Authorization
  # token前缀
  tokenPrefix: "Bearer "
  # JWT密钥
  secret: "your-256-bit-secret-key-for-jwt-token-signature-validation-12345"

# 用户图片上传路径
upload:
  ip: http://127.0.0.1:8080
  path: /www/video/resource/images

# 视频存储配置
video:
  # 视频上传路径
  upload:
    path: /www/video/resource/videos
  # 封面上传路径
  cover:
    path: /www/video/resource/covers
  # 视频访问URL前缀
  access:
    url: http://127.0.0.1:8080/videos

admin:
  jwt:
    # JWT密钥（生产环境请更换为复杂的随机字符串）
    secret: LIGG_PlayVideo_Admin_JWT_Secret_Key_2023
    # 过期时间，单位秒，默认2小时
    expiration: 7200
    # 签发者
    issuer: play-video-admin
#Ip
ip:
  url: http://154.40.44.245:4100,http://154.40.44.245:4000,http://localhost:4100
